model:
  name: GOAT_v2
  multi_omics: True
  params:
    input_dim: 2
    hidden_dim: 4
    output_dim: 4
    num_heads: 2
    num_layers: 2
    dropout: 0.3
    residual: True
    batch_norm: True
    layer_norm: True

optim: 
  optimizer: Adam
  lr: 0.01
  lr_decay: 0
  weight_decay: 0.01

training:
  n_epochs: 1000
  batch_size: 30